# package.yaml
name:                TextAdventureEngine
version:             0.1.0.0
author:              "Nombre del Estudiante 1 y Nombre del Estudiante 2"
maintainer:          "estudiante1@usb.ve, estudiante2@usb.ve"

extra-source-files:
- README.md
- mundo.txt

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  exposed-modules:
  - Engine.Types
  - Engine.Parser
  - Engine.Core
  - Engine.Persistence

executables:
  TextAdventureEngine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TextAdventureEngine